#server
server:
  port: 10010

#log
output:
  ansi:
    enabled: always


#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  web:
    resources:
      static-locations: classpath:/static/

  jpa:
    defer-datasource-initialization: true
    open-in-view: false

  devtools:
    livereload:
      enabled: true

  #    mvc:
  #      static-path-pattern: /static/**




    thymeleaf:
      prefix: classpath:templates/
      suffix: .html
      cache: false
      check-template-location: true

  #jpa
  #  jpa:
  #    hibernate:
  #      ddl-auto: create
  #
  #    #jpa format
  #    properties:
  #      hibernate:
  #        format_sql: true
  #    show-sql: true